Document: ipfinder
Title: Debian ipfinder Manual
Author: <insert document author here>
Abstract: This manual describes what ipfinder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ipfinder/ipfinder.sgml.gz

Format: postscript
Files: /usr/share/doc/ipfinder/ipfinder.ps.gz

Format: text
Files: /usr/share/doc/ipfinder/ipfinder.text.gz

Format: HTML
Index: /usr/share/doc/ipfinder/html/index.html
Files: /usr/share/doc/ipfinder/html/*.html
